# Generated by Django 4.1.3 on 2022-11-19 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=500)),
                ('subject', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('topic', models.ForeignKey(default='Book', on_delete=django.db.models.deletion.SET_DEFAULT, to='Api.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.topic')),
            ],
        ),
    ]
